/**
 * Auto-generated by scripts/generate-image-manifest.mjs — do not edit by hand.
 *
 * Intrinsic dimensions plus an 8x6 PNG blur placeholder for every listing
 * photo, so cards reserve the right aspect box and paint an approximate
 * frame with zero layout shift.
 */
export interface ImageManifestEntry {
  width: number;
  height: number;
  blurDataURL: string;
}

export const imageManifest: Record<string, ImageManifestEntry> = {
  "ashok-leyland-bada-dost": {
    width: 1600,
    height: 1081,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AHBnYmtmZHZyb3Bsa2xmZXlwcHFpbXFkcAB6dWmDfH19eH10dXuMj5KKio6VkZnPzdwAgINuwcGbmZ6cXFtdjYyRgIWUmZeXoJ+gAF1gYo+Xjoh6en9qbY+Eh4iBgYaAf05MTABXVUiJiYuIh4lbX2NeY2VTWV1nbnJsc3YAXGFsVl1qQEZVTFReXmdybHaCdH2Fe4GDa1VDqxRVrUAAAAAASUVORK5CYII=",
  },
  "ashok-leyland-dost": {
    width: 1600,
    height: 1222,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AD9EOzQ9K01XOFRhTy47PDU+PjM7QCw6OQBjZVxKUEpGSz5naGNramZsbmBNVU5obWUAaXNzZnBwVlZNUlhSXGVkiIl+k5OHc3FjAJuvuo+XmaNxOp9/TLO2qqKlm29waH17dgBUWFRBQj0/MSE8MCNXWlVBRD9FR0N7fnoAV1dQTk1ILy8sIiIePjs0amlieHp1cXFs9lw0LbFlVtsAAAAASUVORK5CYII=",
  },
  "ashok-leyland-ecomet": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAn0lEQVR42mOIjQ5NS4kpKU4pK88K9HePC/LIiY/KS01hyEiLz0oOb2rILyjMdHF1jw71K8xOrijJZ+hqLO2tSm5vrC4rqwgPC/b1d8spzotPzmXwdXeNCfUJCw2d0NeRGBfKzMwiK6MgLSXPUF1RPbGnIysrpaQ4R11VSUZCxMPGKMLHmWHD1p1btu+NiY2TlJRwsNCuyQ5oL41tyYsAAOxENRCOAV+iAAAAAElFTkSuQmCC",
  },
  "ashok-leyland-partner": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/ANbUzNTSysrPz8TMzd3c1NLPvNzb1s/NyQDMxrzCu6+ko52ZnZ61q6qSj4N9iYF0fXUAysS92tXLwryyioJ5n4+JgnhyUko8X1FCAMS/uLGroJmTin9tXndzcHBkYX1RQnFLPQCCeW56cGN4b2RcT0JFPTNUUEhRUUxiYVwAhHtxhXxye3NnXFJChIB13dzY6unn+Pj3oR5S+pGzuOQAAAAASUVORK5CYII=",
  },
  "ashok-leyland-tipper": {
    width: 1600,
    height: 898,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AP////////7+/ujm5cfFt2NtRTpIKiUtGAD////////k5N6wrKKppZBiaE4tOSUgKhMA0M7W1tjeoKGblZKEdXVkhIZddn1bSE5AAKqnrK+tsa2jobevqXh0bHd0aq6vo8vNzwDi3NjX09K9v8WzuMKGjJl0fpB/iZ57gI4A1NLU0c/UqK++iJevlqO5iJWsh5KmlJejDHdbBQi5v7AAAAAASUVORK5CYII=",
  },
  "ashok-leyland-viking": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AI+ZpJqkqzhDVEBITGx3fYaNjnmBgpmjpACVmZl/goFIUFVsdHVWcHJNZGhaYWOPlZMApqalbXR0RFBTYmdlY2lmVF1ac3l8m6KkADMzM1daWWlzdZmZlcrIwrSxqouJhmNjYQA5Pj5wbF9gW09iYFiSkYyDfHV1cGZVUkUAOTw7bm1gcG5fXFpMU1FBXFpMdHBfdHReUHM/L6YcFCEAAAAASUVORK5CYII=",
  },
  "bharatbenz-1217": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AFs0PYQ6Q/pVbP9KZP9DWP87T/8wQv8uPAD7SVr/Tmj/Tmn4Rl/vQlfuQVHnQE3mNUIAt2tyn1llm2Ntk2dwhmVsf2JpdmBmcFtiAIOGjUZOUVJVWk9SV1tgZV5iZ1tfZEpNUQCIc3pmam9iZWtlZ2xxc3psbnVmaG9vcXkAoqu1trrBbG9zJCYnOTs+V1pjcHSAb3OAfwBAIsaIsdgAAAAASUVORK5CYII=",
  },
  "bharatbenz-2823": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/ACUkJy8uLSgmJz89P0ZERjw6Ojk4OCgmJgCSocOjrL+0ub59foI2NzooKCxBQ0o+PkMAf4mdsLHF08nRf3V3FxcbIiElT1RkQ0ZTAF1WUpVwdKmBg0EzNU5RVERDRjs7QS0tOABHSE04OD0nJio8Oz5PT1JKSk1TVFpTS0gAREJJQT5CW1hacXBzbmxwR0ZIYmFmbm1xHa0wKjdB7kEAAAAASUVORK5CYII=",
  },
  "eicher-pro-2059": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AEdRQEZLPlRYTJWKbYV8aG9oXFpJNElCLgCVd1Skfl6nhGDAmWvGoHG2iWaud1ald1UAuIFduIllrnpYoo9/r5mHt4xprIFfpH9eALd/WsKTbLmCX5WEgKiblqh6XJ9wTal4VADKjmTSnG3QpXp8X0Z8ZUmsgFt7SCuBRysAuoJT1Ztq4rySy7Gfxq+h3MGo16yCjFo6EUBI/CsGXVoAAAAASUVORK5CYII=",
  },
  "eicher-pro-3015": {
    width: 1600,
    height: 941,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/ALrAx32Gj5WhrZCcqpimt5alt5Cer5CesACorrNTV11sc3t/h5CSnq+TobFveoWcrMIAWVxgMjQ7HiErT1VgU1pmZW56dX+NaHR/ACAiJhYZIAoLEyAiKCMlKzEyNy0rMEVFRwBUVFNGR0lBQkUsLzQdICUeISU2NjZgX10AbWpjbGlmXl5fWVpcUFJVVFRTdXJtbGxr6WU3TpFG2l8AAAAASUVORK5CYII=",
  },
  "force-traveller": {
    width: 1600,
    height: 1116,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AINzJI6AMZuMOIV5Nn9xJ4x3HLWjLMu7OQBtaE+urqu4ubW1tre2tKeclF1pXRpyZRkAgYF7dXRalJOCg4J4b2tnu7iygnxNZ2EjAIJ9bn55caSjqqiorpSSlp6el4SBaHJmRQBQTSY8PTJQUEdZWVFKSkVNTD00Lx0nJBgANzQXQT8VPDoTODETPzoWOjkUQkMXRUUYgXw6ADek06IAAAAASUVORK5CYII=",
  },
  "jcb-backhoe": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AHl1f5GLkpWOlZ+bppiPk4uBhIF3e1ZLTQCUjZCim5yknJ6YkJOmmYunmouGe3pxZWgAnJSUmZKVmpCMn5B6iX9gjH1YiHdtf3V6AH52eIR+g5N9WKN8LktDN2pdQ4l4aIN7gAByam1yaGlnXVlaUk9ZU1R0aFt9dnh4cHUAW1BRZlpcYVZYbmRpZVtfb2x4bm16dG57UftD3L+GZNIAAAAASUVORK5CYII=",
  },
  "mahindra-bolero-pickup": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AIx7ecGzsL23ucm6pp+GZWxTUWlSSn1taQCDV0lvX1WTj4qNhYGRj42jnqJycnNaWmEAX1xNf3lsgX56jJOWhY+ToaSpjY2UPkBDAIJ3dI+HgMC4rLOonbOqo5+cl5aKhG1ZUAB+c3NjVlJGPztNQTpgVk9aVlVjWlaGenkAindxiHZwgG5obV1XWU1IYVNQcWJihnV0IWJEMcCns4gAAAAASUVORK5CYII=",
  },
  "mahindra-furio": {
    width: 1600,
    height: 1361,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AIeDe15cVGpnXYF8cm1pYGllXF9cVDk4MwCJhn5samJ9eXFZV1U2NTIxMS1eXFVGRD8AwL21lZGLr6qhpp6TjYqGcXFvfn14YWBcAH+GiWxoZ2hlYpGGeqmjmXh3cnBvbYB9eQBBPTgxLSkuKicyMDBxb2yXlZGRjYedk4YApY9jeHBmXFdOGRgXGBcXLywqXVNIo5J+pFA6kgwoKfYAAAAASUVORK5CYII=",
  },
  "mahindra-jeeto": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AMvZ6LDCymRud01DQVdMSDk0N21pb4N+gQB5fIBeX2NWVFSFhYRvbW4/PD9FPkFDODgAVVdahX9yi4JwhX9xdG9kc3Bqhnx4aWJdAF5bWD86NE9GOkpBN4RyXJyHda+ond3VwgBPTEpCQkIqKSorJyUpJSFVTkitp5vi2sYAwK+WVE5EX19ZQ0NDNzc4Z2RdysKu1Mq1sDg8qoXSF+8AAAAASUVORK5CYII=",
  },
  "mahindra-supro": {
    width: 1600,
    height: 1067,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AFFQRWNZSEhPNkNJNzpNNlxlQ1tlQ1liRgCIiXJ/h3t9hnxZY1hseWl2gmlqdFdjcE0Atq+nWF5oQEZQPUlcZXWJhJGMl5KFmJWCALu7vVRdaR4pNzlHV2+CloyYobGtq7u2sQDJycyXl5pISlA3PUVCRUtJUFqVl5y8u70AnZqUwsHCs7K2o6KklZWXnpygurm8w8PFxrxE4itU/X4AAAAASUVORK5CYII=",
  },
  "piaggio-ape": {
    width: 1600,
    height: 1060,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAn0lEQVR42mNICPHI83e0dgzyD4lPzs4JjY7o72uOTQlnCHU0rUm38glKCQsListKL6qt6J7QPWFCP4OPlU5ZjJFPYHxUYHRiSkxsbMy82fN6OjsZpkydk5OT5xKc6ewVFRkd7+0X3tLUNm/WNIaEvDanoJzIuAwvD3dbG9uCvNz62ur0xDgGa8+U0pKKmorytKTEytLS5ob66tKy+clFAGLBOdG4JRCCAAAAAElFTkSuQmCC",
  },
  tanker: {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AJKMaYSAXIWEXn+BWXVzWYyBa29oU3VvVwB8e1SCgVqJiGCUinJ6cFuUi3aZkniZj3YAgnpbhoBbuIJrjn+BVVlbgHpolpBybW9PAKWlkKCfgYBWS2dgY3iAhl5aU3t1XnJvUwC7u7+3t7qZnJ2Hh4dubW1tbW2GhYGuq58AoqCit7W2sbGzrKyuqamrsbGzpaWnq6utVthKkQHXCXgAAAAASUVORK5CYII=",
  },
  "tata-1109": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AJKPipOPi4+Oip2ZlLeup5uOgJeGW4d8WACOioNscW5oc3R4gYKJiopjY1KKe1J3bE8AZGVoSlJbUlpdXWVijI9hoKBakoFUd5KoAFteZENHUDM6RThDTpOPPZCRS5WMW4mktwBybGxjYWJbWVY0NjtXVTheXj9NSUp8aV4AlYmBjIeBe3RtaGZlWlhXQ0RHP0FGSEpQjQQ9wggZsIQAAAAASUVORK5CYII=",
  },
  "tata-407": {
    width: 1600,
    height: 1064,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AK+7yrLB0bHC1a2/1qa71qO41JyyzpOnxAC9wsjAxs++x9K4xdOzwdGuvtGnuMyfrsEAwL27vru4rqyqpKSnp6mtnp6hpJuenZ6iAGdjWmhcTks8LzQsJkM3L0Y3LGFFN3RgTQBrVEF8YEuCY0x/Y02CZ1KBZ1V4ZFVsWk8AaFRGbFhKbVpNbFpNZ1ZLZFRKXVBGT0Q+PX5LfVUotuEAAAAASUVORK5CYII=",
  },
  "tata-709": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/ALi3wqWrv4CNq4mWr2lvaoGHl4KMqJWZsACkpquFiI48RlFeaXNJVmFYXWOBg4VQUFIAnp+hcnR3d3h7ioiNiYiNfn6Da2lqTkpOACoqLEpKTHx7gIF9gIaCh3t4fCUjJDYvMQATDw9VUE1cW15LS05XUVVaU1QOCw0NCw0AbV1WST87AwIDBgYGAgICMSkmUkY/CQYHO0M1G8omyTgAAAAASUVORK5CYII=",
  },
  "tata-ace": {
    width: 1600,
    height: 1248,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/ADw+LzY7L0pQO15tTm2BdLG5wMTJzU9dZgA1Ny89QjtjdHV3jI+FjpFucHNuc29yg4wAJCgkQUhPWm2AU2Z8aXWIe4WQh5ilscXQAElPVk5UX0lRYWZpd3d/jGhwe15qdXiFjQCtrqyMjo8oLDMcISkwNT07QUt0eX6trawAoqKil5eYenx9T1VcOEBKkpSVrq2sqqqpncs+0Ch0ZKQAAAAASUVORK5CYII=",
  },
  "tata-intra": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AJqlt5WesJCYqYB9gVNBMlsuHWM2Hmo8GgBjXFWSiISolIyihnWje16nelmtg2i6jWwAdldG0L2w7N7VqJuSgG1el3lfzbOh8cajAIp4bNCzn9/Musazo7+tnYp0ZJN6ad6yjwCuh2qmf2JrUkBmUj1tYE5MQDJmTDigdFYAvpJzt4tuq4FkrYRjlXZSZVkwWkosimlOtdNIprFz3zYAAAAASUVORK5CYII=",
  },
  "tata-lpt-1615": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AEdFQE9OTWFhZXx8gLCwsePi4Kyppn5+fwCDg4KmpaXAv77LzMvx8O7l6uyHlqR9fHwAp6ShhISEkJSYtLW1p6ircHFwUlVXe3p7AF9cW1JVWz9IUVdfaS8uMSknJWBeW3h4eQBaWFkyNDkgIyooKy82NDJcWFRta2pwb28APEBIIyYsERAQPzw4YFxYZ2RjZWRkaWdompg/iRnKBcUAAAAASUVORK5CYII=",
  },
  "tata-marcopolo-bus": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AGpjUllZUk5VS3CBhW+CjJOyv8Po9M/y/gA9OzpGREVMTU5ZYGVwdXdzhIx8k52LoacAPzUvQTc1Qjw8UEQ/Z1pSXVlZWl1fZG5uAGhBL1o3KTgtK1EwJFQ4LFBCOXVxbcbBuAA8Ny4yMy4wNjZLTUtiZ2KQlIq9va/MyLoAVlxPWGBWcHZtjpKHiY2EnJ+VsLCjtrWif5U9AgyYWDEAAAAASUVORK5CYII=",
  },
  "tata-prima": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AFRdXH+HhODm6Oft8MXh9YrG8qfL7a3R7gAuNzBmc3V1gotpdICTnKbS4u/A1ui10OUALzkzXGFrWVZiaHB6m5eXiX5+oaCip6GnACEpLFhaXVlcXn6ChmJeXlhNSklGR3hfWABhV1JGQDstKiUhIyk6Nzk5NTZiV1SShnwAkoFzc2ZeSUNAPzs6cGRdj350oo+DpY5+qeJEQQ2cy3sAAAAASUVORK5CYII=",
  },
  "tata-signa-tipper": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AF9ial5fZT4+PzAvLkVERDc1NTg3NyooKwDV3eje5/C+xtKHjJVAQENEQ0U2NTg8OzkAOi87vq202MXK3MvPuaiqSkVIKS0zTT5GAEA4PHFfYX5qa4Z1d39wcUNAQFRWWVlGXABYWWBNT1VAQUVHSUxSVFdUVFVXV1tlZGwAQEBFRENFTEpMT01NSkhIPTw7NjU0MTAumk408XJ2ay0AAAAASUVORK5CYII=",
  },
  "tata-winger": {
    width: 1600,
    height: 988,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AHRsQI98WYhsTYZyRG5nO2hkM2NhMVFTKwCVjXOws6e2tqvAuq6NiYZ8dHCqfluzhl0AoY52s7Srpaadjo2HUl9qOVFkVVJRj2xRAJyRf6aglcW/tMm+s7azrXWLpFVof5eJdwBrZmJeWVJXUktZVExiXVQ9P0IkKS9QUEsAPj09b2tob2llZWBbXFdTQD4+Pz9CTU5UDjhABci1RNkAAAAASUVORK5CYII=",
  },
  trailer: {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAoUlEQVR42gGWAGn/AEyG2U6J4U2J40+L5FGP6VGR7FCQ61OM4gBMT2NITWhUU2hAS2s2UoJGZ55bfbJ8ndAAeF5FemJSYmdug29udUpIooZRgHZn8e3hAHNMN2plb214ka5nVqdxQrCNQFBJO62qnwB+bFtuY1l5ZlVuWEd/blKKclFhUT1aSzgAbF5Ra11PdGZYemxeeWtee21egnJhf25c/NtAzsM/xiYAAAAASUVORK5CYII=",
  },
  "transit-mixer": {
    width: 1600,
    height: 1066,
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAIAAABxZ0isAAAAnElEQVR42gXBOw6CMAAA0F7CxcVoIhH52AYsBQqUaimkGBDQ+IkS4oiLo7MX9z3geOj7e1V1iTBbWbbheKrpUpUByuJxvHbnjstDdWqa/vkYBiUTkAuexn5EXUJM3pe4TSxjYc8mYL0JqJSIOtCHU31uuvqldTVtCaoijEIYE1MxlGDjKPGtJp/3Hex5KHggUiIYztg257jYESXIHxTAJLHQX4LfAAAAAElFTkSuQmCC",
  },
};
