/**
 * Auto-generated by scripts/generate-image-credits.mjs — do not edit by hand.
 *
 * Attribution for the openly licensed stand-in catalogue photography.
 * Replace these images (and this file) with real listing photos before
 * launch; see README "Catalogue imagery".
 */
import type { VehicleImage } from "@/types/vehicle";

export const imageCredits: Record<
  string,
  NonNullable<VehicleImage["credit"]>
> = {
  "ashok-leyland-bada-dost": {
    author: "Dpb696",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AAshok_Leyland_Dost_Ambulance.jpg",
  },
  "ashok-leyland-dost": {
    author: "Ask27",
    license: "CC BY-SA 3.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AAshok_Leyland_Dost_(1).JPG",
  },
  "ashok-leyland-ecomet": {
    author: "Balaji.B",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AAshok_Leyland_U_truck_-_Chennai_-_India.jpg",
  },
  "ashok-leyland-partner": {
    author: "B Balaji from Chennai, India",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AAshok_Leyland_Truck_(5478313829).jpg",
  },
  "ashok-leyland-tipper": {
    author: "Bairavi Arjunan3",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File%3AMini_tipper_vehicle.jpg",
  },
  "ashok-leyland-viking": {
    author: "Kamal Ratna Tuladhar",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AAshok_leyland_bus_2009.jpg",
  },
  "bharatbenz-1217": {
    author: "For a gallery of some more of my uploaded pictures see: here.",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ABHARATBENZ_Heavy_Duty_Truck_3128_C_front_logo.Spielvogel.JPG",
  },
  "bharatbenz-2823": {
    author:
      "Spielvogel For a gallery of some more of my uploaded pictures see: here. All images can be used free of charge.",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ABharatBenz_3143_Mining_truck._Spielvogel_1.JPG",
  },
  "eicher-pro-2059": {
    author: "IM3847",
    license: "CC BY-SA 4.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AEicher_1095_truck_near_Pedavegi%2C_Eluru.jpg",
  },
  "eicher-pro-3015": {
    author: "Trucksindiawiki",
    license: "CC0",
    source: "https://commons.wikimedia.org/wiki/File%3AEicher_8000.jpg",
  },
  "force-traveller": {
    author:
      "वंपायर;Cropped, minor redrawings, and levels adjusted by uploader Mr.choppers",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AForce_Traveller_Luxury.jpg",
  },
  "jcb-backhoe": {
    author: "Andrey Butko",
    license: "CC BY-SA 3.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AJCB_3CX_backhoe_loader.jpg",
  },
  "mahindra-bolero-pickup": {
    author: "Ilya Plekhanov",
    license: "CC BY-SA 3.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AMahindra_Bolero_Camper_double-cab_truck_in_Pakxe_Laos.jpg",
  },
  "mahindra-furio": {
    author: "Trucksindiawiki",
    license: "CC0",
    source: "https://commons.wikimedia.org/wiki/File%3AEicher_8055.jpg",
  },
  "mahindra-jeeto": {
    author: "Ominae",
    license: "CC BY-SA 4.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AMahindra_Bolero_Double_Cab_Rear.JPG",
  },
  "mahindra-supro": {
    author: "Shadman Samee from Dhaka, Bangladesh",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ABangladesh_Police_(DMP)_Mahindra_Bolero_pickup._(34414736620).jpg",
  },
  "marketing-hero": {
    author: "Biswarup Ganguly",
    license: "CC BY 3.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ALiquid_Petroleum_Gas_Transportation_-_National_Highway_2_-_Burdwan_-_2017-10-21_5067.JPG",
  },
  "piaggio-ape": {
    author: "shankar s. from Dubai, united arab emirates",
    license: "CC BY 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AAn_unusual_goods_carrier_vehicle_(16128927709).jpg",
  },
  tanker: {
    author: "Bernard Gagnon",
    license: "CC BY-SA 4.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATank_truck_on_Phuentsholing-Thimphu_highway%2C_Bhutan.jpg",
  },
  "tata-1109": {
    author: "Shadman Samee from Dhaka, Bangladesh",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATata_LPT_1615_truck_Bangladesh_(24587122563).jpg",
  },
  "tata-407": {
    author: "Biswarup Ganguly",
    license: "CC BY-SA 4.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATata_407_Pickup_Truck_Transportation_-_NH_16_-_Pahal_-_Bhubaneswar_2018-01-26_0193.JPG",
  },
  "tata-709": {
    author: "Biswarup Ganguly",
    license: "CC BY 3.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATATA_1109H_EX2_-_Howrah_2012-08-11_01562.jpg",
  },
  "tata-ace": {
    author: "Everyone Sinks Starco",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATata_Ace_EX2_(21729583101).jpg",
  },
  "tata-intra": {
    author: "Matti Blume",
    license: "CC BY-SA 4.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATata_Ace%2C_Korle-Klottey_(P1100226).jpg",
  },
  "tata-lpt-1615": {
    author: "Shadman Samee from Dhaka, Bangladesh",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AThe_oxygen_truck_Linde_Bangladesh_Tata_LPT_2518._(30612705440).jpg",
  },
  "tata-marcopolo-bus": {
    author: "B25es",
    license: "CC BY-SA 4.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATata_Marcopolo_desembre_MMXXII_03.jpg",
  },
  "tata-prima": {
    author: "Sulthan Naufal",
    license: "CC BY-SA 4.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AMDL_Logistik_TATA_Prima_(BE_9321_CU).jpg",
  },
  "tata-signa-tipper": {
    author:
      "Spielvogel For a gallery of some more of my uploaded pictures see: here. All images can be used free of charge.",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ABharatBenz_3143_Mining_truck._Spielvogel_7.JPG",
  },
  "tata-winger": {
    author: "Shadman Samee from Dhaka, Bangladesh",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3ATata_Winger_van%2C_Bangladesh._(33029016652)_(cropped).jpg",
  },
  trailer: {
    author: "Thank You (21 Millions+) views",
    license: "CC BY 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AColorful_Semi-Trucks.jpg",
  },
  "transit-mixer": {
    author: "woodleywonderworks",
    license: "CC BY 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File%3AClean_concrete_mixer_truck.jpg",
  },
};
